package com.heymoose.domain;

public enum TxType {
  UNKNOWN,
  TRANSFER,
  RESERVATION,
  ACTION_APPROVED,
  MLM,
  RESERVATION_CANCELLED,
  REPLENISHMENT_ROBOKASSA,
  WITHDRAW,
  WITHDRAW_DELETED,
  REPLENISHMENT_ADMIN
}
