//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 06:08:25 PM MSK 
//


package com.heymoose.infrastructure.service.yml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.heymoose.infrastructure.service.yml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.heymoose.infrastructure.service.yml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Volume }
     * 
     */
    public Volume createVolume() {
        return new Volume();
    }

    /**
     * Create an instance of {@link Offers }
     * 
     */
    public Offers createOffers() {
        return new Offers();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link TableOfContents }
     * 
     */
    public TableOfContents createTableOfContents() {
        return new TableOfContents();
    }

    /**
     * Create an instance of {@link HallPart }
     * 
     */
    public HallPart createHallPart() {
        return new HallPart();
    }

    /**
     * Create an instance of {@link PriceMin }
     * 
     */
    public PriceMin createPriceMin() {
        return new PriceMin();
    }

    /**
     * Create an instance of {@link PageExtent }
     * 
     */
    public PageExtent createPageExtent() {
        return new PageExtent();
    }

    /**
     * Create an instance of {@link OrderingTime }
     * 
     */
    public OrderingTime createOrderingTime() {
        return new OrderingTime();
    }

    /**
     * Create an instance of {@link OriginalName }
     * 
     */
    public OriginalName createOriginalName() {
        return new OriginalName();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link WorldRegion }
     * 
     */
    public WorldRegion createWorldRegion() {
        return new WorldRegion();
    }

    /**
     * Create an instance of {@link RecordingLength }
     * 
     */
    public RecordingLength createRecordingLength() {
        return new RecordingLength();
    }

    /**
     * Create an instance of {@link Shop }
     * 
     */
    public Shop createShop() {
        return new Shop();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Tarifplan }
     * 
     */
    public Tarifplan createTarifplan() {
        return new Tarifplan();
    }

    /**
     * Create an instance of {@link IsPremiere }
     * 
     */
    public IsPremiere createIsPremiere() {
        return new IsPremiere();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link PerformanceType }
     * 
     */
    public PerformanceType createPerformanceType() {
        return new PerformanceType();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link Starring }
     * 
     */
    public Starring createStarring() {
        return new Starring();
    }

    /**
     * Create an instance of {@link Days }
     * 
     */
    public Days createDays() {
        return new Days();
    }

    /**
     * Create an instance of {@link Transport }
     * 
     */
    public Transport createTransport() {
        return new Transport();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link CategoryId }
     * 
     */
    public CategoryId createCategoryId() {
        return new CategoryId();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Meal }
     * 
     */
    public Meal createMeal() {
        return new Meal();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link HotelStars }
     * 
     */
    public HotelStars createHotelStars() {
        return new HotelStars();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link ISBN }
     * 
     */
    public ISBN createISBN() {
        return new ISBN();
    }

    /**
     * Create an instance of {@link Additional }
     * 
     */
    public Additional createAdditional() {
        return new Additional();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Storage }
     * 
     */
    public Storage createStorage() {
        return new Storage();
    }

    /**
     * Create an instance of {@link Vendor }
     * 
     */
    public Vendor createVendor() {
        return new Vendor();
    }

    /**
     * Create an instance of {@link TypePrefix }
     * 
     */
    public TypePrefix createTypePrefix() {
        return new TypePrefix();
    }

    /**
     * Create an instance of {@link PerformedBy }
     * 
     */
    public PerformedBy createPerformedBy() {
        return new PerformedBy();
    }

    /**
     * Create an instance of {@link YmlCatalog }
     * 
     */
    public YmlCatalog createYmlCatalog() {
        return new YmlCatalog();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link Part }
     * 
     */
    public Part createPart() {
        return new Part();
    }

    /**
     * Create an instance of {@link Included }
     * 
     */
    public Included createIncluded() {
        return new Included();
    }

    /**
     * Create an instance of {@link Currencies }
     * 
     */
    public Currencies createCurrencies() {
        return new Currencies();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link DataTour }
     * 
     */
    public DataTour createDataTour() {
        return new DataTour();
    }

    /**
     * Create an instance of {@link DeliveryIncluded }
     * 
     */
    public DeliveryIncluded createDeliveryIncluded() {
        return new DeliveryIncluded();
    }

    /**
     * Create an instance of {@link VendorCode }
     * 
     */
    public VendorCode createVendorCode() {
        return new VendorCode();
    }

    /**
     * Create an instance of {@link DeliveryTime }
     * 
     */
    public DeliveryTime createDeliveryTime() {
        return new DeliveryTime();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link PriceMax }
     * 
     */
    public PriceMax createPriceMax() {
        return new PriceMax();
    }

    /**
     * Create an instance of {@link Provider }
     * 
     */
    public Provider createProvider() {
        return new Provider();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Ordering }
     * 
     */
    public Ordering createOrdering() {
        return new Ordering();
    }

    /**
     * Create an instance of {@link Barcode }
     * 
     */
    public Barcode createBarcode() {
        return new Barcode();
    }

    /**
     * Create an instance of {@link Onstock }
     * 
     */
    public Onstock createOnstock() {
        return new Onstock();
    }

    /**
     * Create an instance of {@link Media }
     * 
     */
    public Media createMedia() {
        return new Media();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link Artist }
     * 
     */
    public Artist createArtist() {
        return new Artist();
    }

    /**
     * Create an instance of {@link IsKids }
     * 
     */
    public IsKids createIsKids() {
        return new IsKids();
    }

    /**
     * Create an instance of {@link Director }
     * 
     */
    public Director createDirector() {
        return new Director();
    }

    /**
     * Create an instance of {@link Hall }
     * 
     */
    public Hall createHall() {
        return new Hall();
    }

}
