//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.19 at 06:08:25 PM MSK 
//


package com.heymoose.infrastructure.service.yml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "onstock",
    "ordering",
    "deliveryTime"
})
@XmlRootElement(name = "orderingTime")
public class OrderingTime {

    protected Onstock onstock;
    @XmlElement(required = true)
    protected Ordering ordering;
    protected DeliveryTime deliveryTime;

    /**
     * Gets the value of the onstock property.
     * 
     * @return
     *     possible object is
     *     {@link Onstock }
     *     
     */
    public Onstock getOnstock() {
        return onstock;
    }

    /**
     * Sets the value of the onstock property.
     * 
     * @param value
     *     allowed object is
     *     {@link Onstock }
     *     
     */
    public void setOnstock(Onstock value) {
        this.onstock = value;
    }

    /**
     * Gets the value of the ordering property.
     * 
     * @return
     *     possible object is
     *     {@link Ordering }
     *     
     */
    public Ordering getOrdering() {
        return ordering;
    }

    /**
     * Sets the value of the ordering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ordering }
     *     
     */
    public void setOrdering(Ordering value) {
        this.ordering = value;
    }

    /**
     * Gets the value of the deliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryTime }
     *     
     */
    public DeliveryTime getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * Sets the value of the deliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryTime }
     *     
     */
    public void setDeliveryTime(DeliveryTime value) {
        this.deliveryTime = value;
    }

}
